- for  sentiment analysis i will use fined tuned  model on higgniface

In [23]:
from transformers import pipeline
classifier = pipeline(
    "text-classification",
    model="bhadresh-savani/bert-base-uncased-emotion",
    top_k=None   
)


prediction = classifier("I love using transformers. The best part is wide range of support and its easy to use", )
print(prediction)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bhadresh-savani/bert-base-uncased-emotion
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[[{'label': 'joy', 'score': 0.9972521662712097}, {'label': 'love', 'score': 0.000744332792237401}, {'label': 'anger', 'score': 0.0007404928910546005}, {'label': 'sadness', 'score': 0.0005138235865160823}, {'label': 'surprise', 'score': 0.00041974865598604083}, {'label': 'fear', 'score': 0.00032938565709628165}]]

In [3]:
prediction2 = classifier("I dont like transformers. The worst part is wide range of support and its hard to use", )
print(prediction2)

[{'label': 'anger', 'score': 0.7848674654960632}]

- let's try  with out description in dataset

In [5]:
import pandas as pd

books = pd.read_csv("./dataset/books_cleaned.csv")

In [7]:
books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."

In [8]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [9]:
classifier(books["description"][0])

[{'label': 'sadness', 'score': 0.8875666260719299}]

- when you look at the  whole description it's hard to get  an idea. lets try to break desscription to each sentences and then predict for  each sentence and the take  the count

In [10]:
books["description"][0].split(".")

['A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives',
 ' John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers',
 ' It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up',
 ' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist',
 ' He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption',
 ' Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer',
 ' At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike',
 '']

In [11]:
classifier(books["description"][0].split("."))

[{'label': 'joy', 'score': 0.983815610408783},
 {'label': 'joy', 'score': 0.7085282802581787},
 {'label': 'sadness', 'score': 0.49669545888900757},
 {'label': 'fear', 'score': 0.8844187259674072},
 {'label': 'sadness', 'score': 0.9950024485588074},
 {'label': 'joy', 'score': 0.9979161620140076},
 {'label': 'joy', 'score': 0.9933735132217407},
 {'label': 'anger', 'score': 0.29154807329177856}]

In [13]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [14]:
predictions[0]

{'label': 'joy', 'score': 0.983815610408783}

In [15]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [16]:
predictions[3]

{'label': 'fear', 'score': 0.8844187259674072}

In [17]:
predictions

[{'label': 'joy', 'score': 0.983815610408783},
 {'label': 'joy', 'score': 0.7085282802581787},
 {'label': 'sadness', 'score': 0.49669545888900757},
 {'label': 'fear', 'score': 0.8844187259674072},
 {'label': 'sadness', 'score': 0.9950024485588074},
 {'label': 'joy', 'score': 0.9979161620140076},
 {'label': 'joy', 'score': 0.9933735132217407},
 {'label': 'anger', 'score': 0.29154807329177856}]

- when you look line by line it actually  make  sense

- let's make a  function to  process one  book

In [24]:
def get_emotion_scores(description):
    
    if pd.isna(description):
        return {label: 0 for label in emotion_labels}
    
    sentences = re.split(r'[.!?]', description)
    sentences = [s.strip() for s in sentences if s.strip()]
    
    if len(sentences) == 0:
        return {label: 0 for label in emotion_labels}
    
    predictions = classifier(sentences)
    
    emotion_scores = {label: [] for label in emotion_labels}
    
    for sentence_pred in predictions:
        for item in sentence_pred:
            emotion_scores[item["label"]].append(item["score"])
    
    final_scores = {
        label: np.mean(emotion_scores[label]) if len(emotion_scores[label]) > 0 else 0
        for label in emotion_labels
    }
    
    return final_scores

- apply  to  all  books

In [25]:
all_emotions = []

for i in tqdm(range(len(books))):
    description = books["description"][i]
    scores = get_emotion_scores(description)
    all_emotions.append(scores)

100%|██████████████████████████████████████████████████████████████████████████████| 5197/5197 [31:49<00:00,  2.72it/s]

In [26]:
emotion_df = pd.DataFrame(all_emotions)

In [27]:
emotion_df

       sadness       joy      love     anger      fear  surprise
0     0.236862  0.559227  0.008101  0.026029  0.147438  0.022344
1     0.053362  0.223866  0.033319  0.223530  0.448466  0.017457
2     0.005164  0.961226  0.002978  0.026274  0.003655  0.000702
3     0.024459  0.380926  0.316935  0.027114  0.245057  0.005510
4     0.050179  0.708621  0.010080  0.179401  0.042348  0.009370
...        ...       ...       ...       ...       ...       ...
5192  0.087089  0.395611  0.004107  0.334829  0.119971  0.058393
5193  0.014657  0.840113  0.036340  0.089431  0.013517  0.005942
5194  0.005089  0.976599  0.001658  0.001421  0.011598  0.003634
5195  0.108580  0.600997  0.018060  0.142452  0.124871  0.005040
5196  0.003690  0.854645  0.018585  0.120840  0.001290  0.000950

[5197 rows x 6 columns]

In [28]:
final_df = pd.concat([books, emotion_df], axis=1)

In [29]:
final_df["dominant_emotion"] = final_df[emotion_labels].idxmax(axis=1)

In [30]:
final_df.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,sadness,joy,love,anger,fear,surprise,dominant_emotion
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,0.236862,0.559227,0.008101,0.026029,0.147438,0.022344,joy
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,0.053362,0.223866,0.033319,0.223530,0.448466,0.017457,fear
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",0.005164,0.961226,0.002978,0.026274,0.003655,0.000702,joy
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,0.024459,0.380926,0.316935,0.027114,0.245057,0.005510,joy
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",0.050179,0.708621,0.010080,0.179401,0.042348,0.009370,joy

In [31]:
final_df.to_csv("./dataset/books_with_emotions.csv", index=False)